//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.PowerToys.Run.Plugin.NotionTask.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Community.PowerToys.Run.Plugin.NotionTask.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the default browser.
        /// </summary>
        public static string plugin_browser {
            get {
                return ResourceManager.GetString("plugin_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search a NotionTask package.
        /// </summary>
        public static string plugin_description {
            get {
                return ResourceManager.GetString("plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t include in global results on queries that are URIs.
        /// </summary>
        public static string plugin_global_if_uri {
            get {
                return ResourceManager.GetString("plugin_global_if_uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the default browser.
        /// </summary>
        public static string plugin_in_browser {
            get {
                return ResourceManager.GetString("plugin_in_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In {0}.
        /// </summary>
        public static string plugin_in_browser_name {
            get {
                return ResourceManager.GetString("plugin_in_browser_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotionTask.
        /// </summary>
        public static string plugin_name {
            get {
                return ResourceManager.GetString("plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search the web in {0}.
        /// </summary>
        public static string plugin_open {
            get {
                return ResourceManager.GetString("plugin_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string plugin_result_name {
            get {
                return ResourceManager.GetString("plugin_result_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open {0}..
        /// </summary>
        public static string plugin_search_failed {
            get {
                return ResourceManager.GetString("plugin_search_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The ID of the Notion database containing your tasks.
        /// </summary>
        public static string plugin_notion_database_id {
            get {
                return ResourceManager.GetString("plugin_notion_database_id", resourceCulture);
            }
        }

        /// <summary>
        ///   The secret key to your Notion integration that has access to your task database.
        /// </summary>
        public static string plugin_notion_integration_secret {
            get {
                return ResourceManager.GetString("plugin_notion_integration_secret", resourceCulture);
            }
        }

        /// <summary>
        ///   The sequence of characters that come before the name of the task, when you do not want the task to be opened afterward.
        /// </summary>
        public static string plugin_silent_create {
            get {
                return ResourceManager.GetString("plugin_silent_create", resourceCulture);
            }
        }

        /// <summary>
        ///   The sequence of characters that come before the name of the task; the task will be opened in the web browser afterward.
        /// </summary>
        public static string plugin_create_and_open {
            get {
                return ResourceManager.GetString("plugin_create_and_open", resourceCulture);
            }
        }

        /// <summary>
        ///   The URL of the icon that you wish for the task to have.
        /// </summary>
        public static string plugin_icon_url {
            get {
                return ResourceManager.GetString("plugin_icon_url", resourceCulture);
            }
        }

        /// <summary>
        ///   The URL of the banner that you wish for the task to have.
        /// </summary>
        public static string plugin_banner_url {
            get {
                return ResourceManager.GetString("plugin_banner_url", resourceCulture);
            }
        }
    }
}
